"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wbt&46_nbyw9j+&b!x)!4tj*s0!%*$a*m+k_il#wcgd^cc-_9r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["asianbasket.ie","api.asianbasket.ie","admin.asianbasket.ie"]
#CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=24),
}
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'asianbasket_db',
        'USER': 'asianbasket_user',
        'PASSWORD': 'your_strong_password',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' 
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOWED_ORIGINS = [
    "https://asianbasket.ie",
    "https://www.asianbasket.ie",
    "https://api.asianbasket.ie",
    "https://admin.asianbasket.ie"
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
AUTH_USER_MODEL = 'core.User'



MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"



JAZZMIN_SETTINGS = {
    "site_title": "Asian Basket Admin",
    "site_header": "Asian Basket",
    "site_brand": "Asian Basket",
    "login_logo": None,
    "login_logo_dark": None,
    "site_icon": None,

    "welcome_sign": "Welcome to Asian Basket Admin",
    "copyright": "Asian Basket Ltd",

    "search_model": [
        "auth.User",
        "core.Category",
        "core.SubCategory",
        "core.Product",
    ],

    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
    ],

    "usermenu_links": [
        {"name": "Support", "url": "https://google.com", "new_window": True},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,

    "icons": {
        "auth": "fas fa-users",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users-cog",

        "core.Category": "fas fa-list",
        "core.SubCategory": "fas fa-tags",
        "core.Product": "fas fa-box",
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    "custom_css": None,
    "custom_js": None,
}
# ===============================
# REVOLUT CONFIG
# ===============================

from dotenv import load_dotenv
load_dotenv()

#REVOLUT_SECRET_KEY = "sk_-D__Ba0UFVFykla-DEseC0uiszRHDPEvfn9fsEyu3Q2aUrTCyD8ZnnMFqq38cSOy"
#REVOLUT_PUBLIC_KEY = "pk_iESyilztHaw6iyCOI85pf3WqhLBKuY1CwMYoCv850g9k6WQX"
REVOLUT_SECRET_KEY="sk_UaVIr7i9p6HSGQCQlPPuLVwFzMC456gkOIKqXfmZFaWqGB6L5RpMPY9CYG1wTwSo"
REVOLUT_PUBLIC_KEY="pk_TTEe2kSP8MzZV6cfutzIfSzhlqDPPbhKWhNLoD2CpD5s9qIy"
#REVOLUT_BASE_URL = "https://merchant.revolut.com/api/1.0"
REVOLUT_BASE_URL ="https://merchant.revolut.com/api/orders"
# ✅ CRITICAL FIX
# FRONTEND_URL = "http://localhost:5173"
FRONTEND_URL = "https://asianbasket.ie/"

BACKEND_PUBLIC_URL = "https://api.asianbasket.ie/"

#REVOLUT_WEBHOOK_SIGNING_SECRET="wsk_Us2HFPJuKiB307kcpzjBJOGE4PPQoTqd"
REVOLUT_WEBHOOK_SIGNING_SECRET="wsk_9R6WqsCUWsKWauwHuFtTu0OkoqaE7Zu3"
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
