# Generated by Django 4.2.7 on 2026-03-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('validity', models.CharField(blank=True, max_length=100)),
                ('badge_type', models.CharField(choices=[('percent', 'Percent Off'), ('bogo', 'Buy 1 Get 1'), ('delivery', 'Free Delivery'), ('flat', 'Flat Off'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
