# Generated by Django 4.2.7 on 2026-03-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-priority', '-in_stock', '-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category'], name='core_produc_is_acti_111e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'subcategory'], name='core_produc_is_acti_37301b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_trending'], name='core_produc_is_acti_383610_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-priority', '-in_stock'], name='core_produc_priorit_fdc417_idx'),
        ),
    ]
